import type {Evidence} from './game-model';

// Exact excerpts from the synthetic frozen corpus used in the October 4 benchmark.
// These are intentionally shipped examples, not a claim of live source verification.
export const initialEvidence: Evidence[] = [
  {id: '01-deployment-record.md', title: 'Deployment record', text: 'The release changed the payment-provider request timeout from 10 seconds to 4 seconds. The stated purpose was to fail fast and allow the customer interface to show a retry option sooner.\n\nThe release did not include a postal-code validation rule change. It also did not include a fraud-rule configuration change.', provenance: '01-deployment-record.md · exact excerpt · frozen synthetic benchmark corpus, October 4, 2026', kind: 'frozen-source'},
  {id: '02-provider-latency-log.md', title: 'Provider A latency observation', text: "Between 10:00 and 10:15 UTC, Provider A's p95 authorization latency rose from a usual range below 1.2 seconds to between 4.8 and 7.1 seconds. Timeout events from the checkout service rose during the same window.\n\nThis observation does not prove that Provider A was the sole cause. The sample excludes payments routed to other providers and does not contain a provider-authenticated root-cause statement.", provenance: '02-provider-latency-log.md · two exact paragraphs · frozen synthetic benchmark corpus, October 4, 2026', kind: 'frozen-source'},
  {id: '03-postal-code-sample.md', title: 'Postal-code sample', text: 'No single postal-code format, country, or validation message appeared in more than three of the 40 records. Thirty-one of the 40 customers later completed payment without editing their postal code.\n\nThis limited sample weakens the hypothesis that a postal-code validation change was the primary explanation for the incident. It cannot exclude an unrelated address-validation defect outside the sampled records.', provenance: '03-postal-code-sample.md · exact excerpt · frozen synthetic benchmark corpus, October 4, 2026', kind: 'frozen-source'},
  {id: '04-fraud-score-report.md', title: 'Fraud decision comparison', text: "For the incident window, the fraud service's approval, review, and decline distribution was compared with the same weekday baseline. No material change was observed. The fraud-rule configuration audit also recorded no rule publication between 08:00 and 12:00 UTC.\n\nThe affected checkout attempts were primarily recorded as service timeouts rather than fraud declines.", provenance: '04-fraud-score-report.md · exact excerpt · frozen synthetic benchmark corpus, October 4, 2026', kind: 'frozen-source'},
  {id: '05-provider-status-update.md', title: 'Provider status update', text: 'At 10:12 UTC, Provider A published a status update reporting elevated authorization latency for part of its regional processing network. The notice did not identify a root cause and did not list all affected merchants or transactions.\n\nThe notice is not sufficient evidence to conclude that every observed payment failure originated with Provider A.', provenance: '05-provider-status-update.md · two exact paragraphs · frozen synthetic benchmark corpus, October 4, 2026', kind: 'frozen-source'},
  {id: '06-provider-a-july-maintenance.md', title: 'A similar-looking older outage', text: '# July maintenance\n\n**Incident/window:** 2026-07-11 01:00–02:00 UTC\n\nProvider A planned maintenance caused a separate outage. This is not the September checkout incident.', provenance: '06-provider-a-july-maintenance.md · full body · frozen synthetic benchmark corpus, October 4, 2026', kind: 'frozen-source'},
];
